services:
  www:
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/www/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - api
      - db
      - redis
    environment:
      - PUBLIC_API_URL=http://localhost:8000
      - INTENRAL_API_URL=http://api:8000
      - API_KEY=foobar

  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - 8000:8000
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://postgres:postgres@db:5432/shihai
      - API_KEY=foobar
    depends_on:
      - redis
      - db

  redis:
    image: redis:7.4.1
    restart: unless-stopped
    volumes:
      - redis_data:/data

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=shihai
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:
