services:
  www:
    image: ghcr.io/omfj/shihai-www:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - api
      - db
      - redis
    environment:
      - PUBLIC_API_URL=http://localhost:8000
      - INTENRAL_API_URL=http://api:8000
      - API_KEY=SOME_STRONG_SECRET

  api:
    image: ghcr.io/omfj/shihai-api:latest
    restart: always
    ports:
      - 8000:8000
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://postgres:SOME_STRONG_DB_PASSWORD@db:5432/shihai
      - API_KEY=SOME_STRONG_SECRET
    depends_on:
      - redis
      - db

  redis:
    image: redis:7.4.1
    restart: unless-stopped
    volumes:
      - redis_data:/data

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SOME_STRONG_DB_PASSWORD
      - POSTGRES_DB=shihai
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  postgres_data:
